### ISSUE TITLE
Problème utilisation bloc de température

### ISSUE THREAD

**Issue by bertinmaghit** [LabAixBidouille-STM32/pxt-stm32-iot-node#10]
Bonjour,

Dans la version de la béta 0.4.3 , lorsqu'on utilise le bloc de température, si on place une valeur même à 100°C la led reste allumée alors que la température est largement en dessous.

![image](https://user-images.githubusercontent.com/45633641/49525547-4c208e00-f8ae-11e8-954f-f00497deb731.png)

Le code Java est:

> input.onTemperatureConditionChanged(TemperatureCondition.Hot, 200, TemperatureUnit.Celsius, function () {
    pins.LED2.digitalWrite(true)
})
pins.LED.digitalWrite(false)

Testé avec Windows 10 sous Firefox.

**Comment by nedseb** [comment]
Tiens c'est étrange comme comportement.... Je vais essayer de reproduire l'exemple pour mieux comprendre d'où ça peut venir.

**Comment by nedseb** [comment]
Je pense que ça doit venir de l'initialisation. Sur les deux premières secondes d'utilisation d'un capteur j'ai souvent des valeurs fausses qui se stabilisent au bout de quelques secondes. Je travaille aujourd'hui sur l'issue #13 pour qu'on puisse être certain de l'origine du problème

**Comment by bertinmaghit** [comment]
Bonjour,
Merci, est ce qu'on pourrait en même temps améliorer la phrase:

"la température devenant plus HOT/COLD à 200 °c"

Et la remplacer plutôt par:

"la température est SUPERIEURE/INFERIEURE à 200 °c"

**Comment by nedseb** [comment]
Bonsoir,
Pour les formulations, le mieux est d'aller directement sur l'outil de traduction : https://crowdin.com/project/kindscript/fr
Il est ouvert à tous, donc il ne faut pas hésiter à contribuer. Actuellement la traduction est encore assez partielle mais il faudra améliorer les choses pour le lancement final

**Comment by nedseb** [comment]
Je viens de vérifier l'exemple avec le LCD Grove et ça semble fonctionner correctement depuis la v0.5.2
