### ISSUE TITLE
Bloc pression

### ISSUE THREAD

**Issue by bertinmaghit** [LabAixBidouille-STM32/pxt-stm32-iot-node#11]
Bonjour,

Dans le bloc de la pression de la version beta 0.4.3, l'info bulle d'aide ne correspond pas. Il apparait les informations de la bulle d'info de l'humidité.

![image](https://user-images.githubusercontent.com/45633641/49525814-d36e0180-f8ae-11e8-81a2-70f4ca64d791.png)

Utilisé sous Windows 10 avec Firefox

Eric

**Comment by nedseb** [comment]
Bonjour Éric,
Je fais la correction immédiatement. Merci beaucoup pour cette contribution car je ne l'aurai jamais vu ;)
Sébastien

**Comment by nedseb** [comment]
Corrigé à partir de la v0.4.4

**Comment by bertinmaghit** [comment]
Bonjour,

Est ce qu'on pourrait changer la phrase par:

La pression est SUPERIEURE/INFERIEURE à 1013 hPa
