### ISSUE TITLE
Le débogage est impossible sans écran

### ISSUE THREAD

**Issue by nedseb** [LabAixBidouille-STM32/pxt-stm32-iot-node#13]
(question posée par mail)

Actuellement il est assez délicat de vérifier le bon fonctionnement des différents capteurs sans un moyen d'affichage de leurs valeurs. Serait-il possible de bousculer le plan de développement pour bénéficier du LCD Grove plus rapidement ?

**Comment by nedseb** [comment]
Je m'occupe de livrer le LCD au plus vite. Idéalement j'espère arriver à l'ajouter dans la version v0.5 de ce soir

**Comment by droussel3** [comment]
on arrive à se débrouiller avec les debugger qui affiche les valeurs des variables...

**Comment by nedseb** [comment]
Je viens de rajouter le support du LCD ça permettra de plus facilement tester les capteurs en dehors du simulateur
