### ISSUE TITLE
incrémentation des fonctions

### ISSUE THREAD

**Issue by droussel3** [LabAixBidouille-STM32/pxt-stm32-iot-node#14]
je pense que lorsque l'on passe de JavaScript à block les foncstions sont incrémentés.. on se retrouve avec des drôles de noms... 
![image](https://user-images.githubusercontent.com/32913098/49638426-67071580-fa08-11e8-9491-8dffc0ab1271.png)

merci

**Comment by nedseb** [comment]
Bonjour,
C'est un problème interne à makecode. Il faudrait ouvrir une issue similaire sur le dépot Microsoft (https://github.com/Microsoft/pxt/issues) pour espérer qu'ils corrigent ce problème dans les prochaines versions.
