### ISSUE TITLE
nombre de led (digital ou analogique limitée à 7)

### ISSUE THREAD

**Issue by droussel3** [LabAixBidouille-STM32/pxt-stm32-iot-node#15]
J'ai voulu simuler le fonctionnement d'un octet (8 bit) mais le simulateur ne fonctionne plus lorsque l'on dépasse 7 led
Est-ce un bug ou c'est normal ?

![image](https://user-images.githubusercontent.com/32913098/49638671-278cf900-fa09-11e8-92cb-27338bede96d.png)

**Comment by nedseb** [comment]
C'est une limitation dûe à la taille de la breadboard du simulateur... Quand on dépasse les 30 colonnes, le simulateur s’arrête. On peut ouvrir une issue chez microsoft pour leur demander d'ajouter de la place sur cette breadboard (https://github.com/Microsoft/pxt/issues)
