### ISSUE TITLE
Problème de simulation écran LCD

### ISSUE THREAD

**Issue by Steph77** [LabAixBidouille-STM32/pxt-stm32-iot-node#17]
Bonjour Sébastien,
Afin de tester l'affichage des couleurs de l'écran LCD, j'ai réalisé le programme suivant :

![iotnode-capture d ecran 7](https://user-images.githubusercontent.com/11035731/49761206-a95d7a80-fcc6-11e8-9e0b-8f7b2387df74.png)

Il fonctionne correctement lorsque la carte est programmée et l'on peut voir les variations de la couleur de l'écran. Par contre, en mode simulation, l'écran reste sur la couleur verte.

**Comment by nedseb** [comment]
Bonjour Stéphane,
Visiblement c'est un problème avec la présence de deux blocs "toujours". Pour le coup, je ne sais pas si ce bug ne proviendrait pas du simulateur de makecode car j'ai l'impression qu'il ne lance qu'un seul des deux blocs "toujours". Résultat pour celui qui n'est pas lancé, la visualisation n'est pas mise à jour. Il faudrait regarder s'il en est de même sur les autres cibles makecode.
Bonne journée

**Comment by nedseb** [comment]
Alors je ne comprends pas d'ou ça vient car ça marche sur microbit

**Comment by nedseb** [comment]
Alors après investigation, j'ai rencontré le même problème sur makecode.adafruit.com. Le problème est rentré dans l'ordre en relançant le simulateur. J'ai l'impression que l'ajout d'un second bloc "toujours" n'est pas pris en compte immédiatement et que tant qu'on relance pas le simulateur seul l'un des deux se lance.

De mon coté, j'ai testé avec ce code et ça semble fonctionner : 

```js
let a = 0
a = 0
forever(function () {
    pause(100)
    LCD.clear()
    LCD.setCursor(0, 0)
    LCD.ShowNumber(a)
    LCD.SetBacklightColor(LCD.rgb(255 - a, a, 255))
})
forever(function () {
    pause(100)
    a += 1
    if (a >= 255) {
        a = 0
    }
})
```
