### ISSUE TITLE
Capteur de distance

### ISSUE THREAD

**Issue by Steph77** [LabAixBidouille-STM32/pxt-stm32-iot-node#18]
Bonjour Sébastien,
Petit retour concernant le capteur de distance.
Comme nous l'avions évoqué, avec le shield de connexion Grove, la mesure est erronée. Le shield vient se positionner juste à la limite du capteur, j'obtiens ce résultat : 
![48270681_377601069668120_4322814017111326720_n](https://user-images.githubusercontent.com/11035731/49866915-5809d400-fe09-11e8-8d4c-bbf9e86a386b.jpg)

En enlevant le shield grove et en positionnant un obstacle à 10cm, la mesure indiquée me semble assez imprécise : 
![48020975_285968925599604_3237075722388373504_n](https://user-images.githubusercontent.com/11035731/49866970-7a9bed00-fe09-11e8-8a2a-59d9a9f67f52.jpg)
![48333206_393323428071431_8549614177759526912_n](https://user-images.githubusercontent.com/11035731/49866981-7c65b080-fe09-11e8-97ec-fb74a57c1e09.jpg)
Voici le code  : 
![iotnode-capture d ecran](https://user-images.githubusercontent.com/11035731/49867069-adde7c00-fe09-11e8-89a2-76efa03738f3.png)

Bonne journée,

Stéphane

**Comment by nedseb** [comment]
Le problème vient du film orange présent sur le capteur quand la carte est neuve. Attention à toujours penser à lever ce film pour avoir de bonnes valeurs
