### ISSUE TITLE
Affichage de la température erroné sur écran LCD

### ISSUE THREAD

**Issue by Steph77** [LabAixBidouille-STM32/pxt-stm32-iot-node#19]
Sébastien,
Je rencontre le souci suivant avecl'affichage de la température sur un écran LCD :
L'affichage dans le simulateur est correct 
![image](https://user-images.githubusercontent.com/11035731/49868468-d4061b00-fe0d-11e8-982c-53f8ae5c3952.png)
mais une fois la carte programmée, l'affichage de la température semble devoir être divisé par 10 pour obtenir la bonne valeur : 
![2373978407084069243](https://user-images.githubusercontent.com/11035731/49868508-f13ae980-fe0d-11e8-8566-574928be8259.jpg)

**Comment by nedseb** [comment]
En effet.... Je corrige ça immédiatement
