### ISSUE TITLE
Simulation plante avec l'ajout de "ON BUTTON USER CLICK"

### ISSUE THREAD

**Issue by Steph77** [LabAixBidouille-STM32/pxt-stm32-iot-node#6]
Si l'on ajoute le bloc "on button user click", le simulateur plante
Si l'évènement concerne une autre entrée (A0 par exemple), cela fonctionne à nouveau
Par contre, la carte programmée fonctionne correctement".

Programme de test utilisé : https://makecode.com/_TFkceJ3YdFKw

**Comment by nedseb** [comment]
Fonctionne sur la version 0.0.64
