### ISSUE TITLE
Boucle "toujours" qui ne répète pas avec le capteur d'humidité

### ISSUE THREAD

**Issue by Steph77** [LabAixBidouille-STM32/pxt-stm32-iot-node#7]
**Describe the bug**
J'ai testé ce programme : 
![iotnode-capture d ecran 2](https://user-images.githubusercontent.com/11035731/49258364-7ea53380-f435-11e8-90bb-1bd927ddfabd.png)
La boucle se répète bien dans le simulateur mais pas dans la carte programmée.

En utilisant le capteur de température, cela fonctionne correctement dans le simulateur et la carte :![iotnode-capture d ecran 3](https://user-images.githubusercontent.com/11035731/49258428-b7450d00-f435-11e8-867c-752e093063de.png)

Si j'utilise une variable intermédiaire pour stocker le % d'humidité, la DEL clignote en permanence : 
![iotnode-capture d ecran 4](https://user-images.githubusercontent.com/11035731/49258508-fa06e500-f435-11e8-8109-72f95b05043c.png)

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.102

**Comment by nedseb** [comment]
Bonjour Stéphane,
Je viens de vérifier, il y a effectivement une erreur de plage de valeur entre la carte et la simulation. Dans la version v0.2.2, la carte retourne une valeur dans une plage la plage [0, 1000] et il y a eu une inversion de sens dans le passage d'une plage vers l'autre.

Je regarde s'il n'y pas pas d'autres problèmes et je fais une nouvelle version beta.

Merci beaucoup pour ce retour

Sébastien

**Comment by nedseb** [comment]
Bonjour Stéphane,
J'ai l'impression que c'est rentré dans l'ordre, tu peux me confirmer ?
Bonne journée

Sébastien

**Comment by Steph77** [comment]
Bonjour Sébastien,
Je viens de tester avec le simulateur et l'écran LCD, je n'ai pas d'actualisation de l'affichage des données : 
https://makecode.com/_CH6a0KAkM7re
![iotnode-capture d ecran](https://user-images.githubusercontent.com/11035731/49732995-ab9ce600-fc80-11e8-87b0-fbcd2f4bad4d.png)
Bonne journée également,

Stéphane

**Comment by nedseb** [comment]
Attention, `clear screen` ne repositionne pas le curseur donc ce programme doit t'afficher un écran vide car les 8 premiers affichages ont lieux mais après tu écris en dehors de l'écran et tu efface le contenu précédent. As-tu bien ce comportement ?

pour avoir un affichage propre d'une valeur, on est obligé d'effacer l'écran, se positionner comme il se doit et enfin on écrit. Actuellement je trouve ça un peu lourd c'est pour ça que j'avais fait les blocs avec positionnement mais je ne suis pas plus convaincu c'est pour ça que je les ai mis dans la section "more"...
 ```js
forever(function () {
    LCD.clear()
    LCD.setCursor(0, 0)
    LCD.ShowValue("T", input.temperature(TemperatureUnit.Celsius))
})
```

**Comment by Steph77** [comment]
Effectivement, cela fonctionne bien !
Merci beaucoup.
