### ISSUE TITLE
Problème affichage des blocs pour chaque nouvel exemple

### ISSUE THREAD

**Issue by technoarbaud** [LabAixBidouille-STM32/pxt-stm32-iot-node#9]
Salut Sébastien,
Dans makecode st version 0.0.64 (pas la béta) les élèves ou même les adultes n'arrive pas à charger un exemple la première fois si la carte n'est pas connecté.
Message d'erreur qui écrit juste "appareil" comme si il attend un  appareil 
En retournant sur l'accueil il faut recharger un nouvel exemple et là c'est bon ...
Testé avec windows 10 et firefox
également tablette du CD13 

merci

Olivier Lagay

.

**Comment by nedseb** [comment]
Bonjour Olivier,
J'avais eu ce problème effectivement sur la v0.0.64. Je l'ai corrigé avant la phase beta. Je vais faire avancer la version stable juste avant l'ajout de la température pour régler ce problème. Sache que si d'aventure tu revois cet écran, un appui sur la touche 'Echap' le fait disparaitre.
Bonne journée

Sébastien

**Comment by nedseb** [comment]
J'ai fait avancer la version stable à la v0.0.67. J'ai encore le problème de manière aléatoire... Je vais bien revérifier si je ne l'ai plus aussi sur la beta

**Comment by nedseb** [comment]
Je vais faire avancer la stable d'ici demain. Ce problème ne devrait plus exister. Je cloture l'issue, ne pas hésiter à la rouvrir si le problème persiste
